- name: "virtual_server.pool: Ensure state of pool"
  bigip_pool:
    server: "{{ ansible_host | default(omit) }}"
    server_port: "{{ ansible_httpapi_port | default(omit) }}"
    partition: "{{ bigip_virtual_server.partition | default(omit) }}"
    name: "{{ bigip_pool.name }}"
    state: "{{ bigip_pool.state | default(omit) }}"

- name: "virtual_server.pool: Ensure association between pool and virtual_server"
  bigip_virtual_server:
    server: "{{ ansible_host | default(omit) }}"
    server_port: "{{ ansible_httpapi_port | default(omit) }}"
    partition: "{{ bigip_virtual_server.partition | default(omit) }}"
    name: "{{ bigip_virtual_server.name }}"
    pool: "{{ bigip_pool.name }}"
    state: "{{ bigip_pool.state | default(omit) }}"

- include_tasks: virtual_server.pool.members.yml
