---
- name: "Rollback to startup-config"
  bigip_command:
    server: "{{ ansible_host | default(omit) }}"
    server_port: "{{ ansible_httpapi_port | default(omit) }}"
    commands: "load sys config"