---
- name: "Save running-configuration"
  bigip_command:
    server: "{{ ansible_host | default(omit) }}"
    server_port: "{{ ansible_httpapi_port | default(omit) }}"
    commands: "save sys config"