---
- name: Configure the F5s hosts
  hosts: linux:&web
  become: yes
  gather_facts: no
  tasks:
    - name: Ensure state of httpd package
      yum:
        name: httpd
        state: present

    - name: Ensure state of httpd service
      service:
        name: httpd
        state: started
