---
- name: "Configure F5: time settings"
  hosts: tmos:&{{ bigip_server }}
  connection: local
  gather_facts: no
  roles:
    - role: f5devcentral.f5ansible

  tasks:
    - name: Ensure state of NTP settings
      bigip_device_ntp:
        server: "{{ ansible_host | default(omit) }}"
        server_port: "{{ ansible_httpapi_port | default(omit) }}"
        ntp_servers: "{{ bigip_device_ntp_servers | default(omit) }}"
        timezone: "{{ bigip_device_ntp_timezone | default(omit) }}"