---
- name: "Configure F5: pool and members"
  hosts: tmos:&{{ bigip_server }}
  connection: local
  gather_facts: no
  roles:
    - role: f5devcentral.f5ansible

  tasks:
    - name: Ensure state of pool settings
      bigip_pool:
        server: "{{ ansible_host | default(omit) }}"
        server_port: "{{ ansible_httpapi_port | default(omit) }}"
        partition: "{{ bigip_partition | default(omit) }}"
        name: "{{ bigip_pool_name }}"
        state: "{{ bigip_pool_state | default(omit) }}"

    - name: Ensure state of node and pool membership
      bigip_pool_member:
        server: "{{ ansible_host | default(omit) }}"
        server_port: "{{ ansible_httpapi_port | default(omit) }}"
        partition: "{{ bigip_partition | default(omit) }}"
        pool: "{{ bigip_pool_name }}"
        name: "{{ bigip_member_name }}"
        address: "{{ bigip_member_address }}"
        port: "{{ bigip_member_port | default(omit) }}"
        state: "{{ bigip_member_state | default(omit) }}"