---
- name: "Configure F5: VLANs and interfaces"
  hosts: tmos:&{{ bigip_server }}
  connection: local
  gather_facts: no
  roles:
    - role: f5devcentral.f5ansible

  tasks:
    - name: Ensure state of VLAN interfaces
      bigip_vlan:
        server: "{{ ansible_host | default(omit) }}"
        server_port: "{{ ansible_httpapi_port | default(omit) }}"
        name: "{{ bigip_vlan_name }}"
        untagged_interfaces: "{{ bigip_vlan_untagged_interfaces | default(omit) }}"
        tagged_interfaces: "{{ bigip_vlan_tagged_interfaces | default(omit) }}"